#!/usr/bin/python

import sys, re


regex_hexwordbytes = r"([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})([0-9a-fA-F]{2})"
regex_hexword = r"([0-9a-fA-F]+)"
regex_memline = r"^\s*([0-9a-fA-F]+)\s+([0-9a-fA-F]+\w)+"
regex_memline = r"^\s*([0-9a-fA-F]+)\s+(([0-9a-fA-F]+\s+)+)"

for line in sys.stdin:
    memline = re.match(regex_memline, line, flags=0)
    if(memline):
        #memline_LE = "@" + memline.group(1)
        words = memline.group(2).split()
        for word in words:
            word_BE = "00000000" + word
            byte3 = word[-2:]
            byte2 = word[-4:-2]
            byte1 = word[-6:-4]
            byte0 = word[-8:-6]
            memline_LE = byte3 + byte2 + byte1 + byte0
            print memline_LE
        
